# Generated by Django 5.0.4 on 2024-05-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricecard',
            name='pc_title',
            field=models.CharField(default='жалупа', max_length=100, null=True, verbose_name='Title'),
        ),
    ]
