# Generated by Django 5.0.4 on 2024-05-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cms_slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cms_img', models.ImageField(upload_to='slider_img/')),
                ('cms_title', models.CharField(max_length=20, verbose_name='Title')),
                ('cms_text', models.CharField(max_length=20, verbose_name='Text')),
            ],
            options={
                'verbose_name': 'Slider',
            },
        ),
    ]
