# Generated by Django 5.0.4 on 2024-05-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_token', models.CharField(max_length=50, verbose_name='Bot token')),
                ('tg_chat', models.CharField(max_length=100, verbose_name='Chat ID')),
                ('tg_message', models.TextField(verbose_name='Message')),
            ],
        ),
    ]
