# Generated by Django 5.0.4 on 2024-05-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(max_length=150)),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('order_phone', models.CharField(max_length=30)),
            ],
        ),
    ]
