# Generated by Django 5.0.4 on 2024-05-23 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_statuscrm_alter_order_order_phone_order_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentCrm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_comment', models.TextField(verbose_name='CRM Comment')),
                ('comment_date', models.DateTimeField(auto_now=True, verbose_name='Created at')),
                ('comment_binding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.order', verbose_name='binding')),
            ],
        ),
    ]
